name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova project
        run: |
          cordova create app com.example.soulfragments "Soul Fragments"
          cp -r www app/www
          cp config.xml app/
          cd app
          cordova platform add android
          cordova build android --release

      - name: Upload APK
        uses: uses: actions/upload-artifact@v4
        with:
          name: SoulFragments-APK
          path: app/platforms/android/app/build/outputs/apk/release/*.apk
